server:
  port: 9090

security:
  oauth2:
    client:
      client-id: appclient
      client-secret: appclient@123
    resource:
      id: carInventory
      token-info-uri: http://localhost:8080/oauth/check_token