spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/oauth2_database
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

# --- server
server:
  port: 8081
