server:
  port: 8083

spring:
  h2:
    console.enabled: true
    path: /h2-console
    settings.trace: false
    settings.web-allow-others: false
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: test
    realmImportFile: syspro-realm.json
