server:
  port: 7777


security:
  oauth2:
    client:
      client-id: javadeveloperzone
      client-secret: secret
    resource:
      id: txtInventory
      token-info-uri: http://localhost:8080/oauth/check_token