server:
  port: 9081

logging.level.root: DEBUG
logging.level.org.springframework.web: DEBUG

#security:
#  oauth2:
#    client:
#      clientId: exampleClient
#      clientSecret: exampleSecret
#    resource:
#      token-info-uri: http://localhost:8080/oauth/check_token
