server: 
  port: 8081
  servlet: 
    context-path: /sso-resource-server

####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/syspro
          jwk-set-uri: http://localhost:8083/auth/realms/syspro/protocol/openid-connect/certs
  jpa:
    defer-datasource-initialization: true