spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    jdbc-url: jdbc:postgresql://localhost:5432/oauth2_database
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
#    jdbc-url: jdbc:mysql://localhost/oauth2
    jpa:
      hibernate:
        ddl-auto: none
# --- server
server:
  port: 8083
